# Generated by Django 3.2.25 on 2024-12-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='framedetection',
            name='frame_filename',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
