# Generated by Django 3.2.25 on 2024-12-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_tracker', '0002_framedetection_frame_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framedetection',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='framedetection',
            name='detection_class',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
