# Generated by Django 3.2.25 on 2024-12-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_tracker', '0003_auto_20241223_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framedetection',
            name='frame_filename',
            field=models.FileField(upload_to='frames/'),
        ),
    ]
