# Generated by Django 3.2.25 on 2024-12-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_tracker', '0009_youtubevideo_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='anger',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='happy',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='panic',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='sadness',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
