# Generated by Django 3.2.25 on 2024-12-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_tracker', '0010_auto_20241225_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='anger',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='happy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='panic',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='sadness',
            field=models.IntegerField(default=0),
        ),
    ]
