# Generated by Django 3.2.25 on 2024-12-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_tracker', '0011_auto_20241225_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
